// export { default as Swatch } from './Swatch'
export { default as ImageGallery } from './Gallery'
export { default as ProductView } from './View'
export { default as ProductCard } from './ProductCard'
export { default as ProductSlider } from './Slider'
export { default as ProductOption } from './Option'
export { default as ProductTag } from './Tag'
export { default as ProductSidebar } from './Sidebar'
export { default as ProductDescription } from './Description'
export { default as ProductInfo } from './Info'
export { default as ProductReview } from './Review'
export { default as RelatedProducts } from './Related'
export { default as Thumbnail } from './Thumbnail'
export { Stars, Comments } from './Review'
